name: docker-build-cache-config
description: Effective cache with docker/build-push-action for pull request based development flow

inputs:
  image:
    description: image name to import/export cache
    required: true
  flavor:
    description: flavor
    required: false
  tag-prefix:
    description: prefix of image tag
    required: false
    deprecationMessage: |
      use `flavor: prefix=`
  tag-suffix:
    description: suffix of image tag
    required: false
    deprecationMessage: |
      use `flavor: suffix=`
  extra-cache-from:
    description: extra flag to cache-from
    required: false
  extra-cache-to:
    description: extra flag to cache-to
    required: false
  token:
    description: token to access github api
    required: false
    default: ${{ github.token }}
  pull-request-cache:
    description: flag to enable Pull request dedicated cache
    required: false
    default: 'false'

outputs:
  cache-from:
    description: cache-from parameter
  cache-to:
    description: cache-to parameter

runs:
  using: 'node20'
  main: 'dist/index.js'
