name: docker-build-cache-config
description: Effective cache with docker/build-push-action for pull request based development flow

inputs:
  image:
    description: image name to import/export cache
    required: true
  flavor:
    description: flavor
    required: false
  tag-prefix:
    description: prefix of image tag
    required: false
    deprecationMessage: |
      use `flavor: prefix=`
  tag-suffix:
    description: suffix of image tag
    required: false
    deprecationMessage: |
      use `flavor: suffix=`

outputs:
  cache-from:
    description: cache-from parameter
  cache-to:
    description: cache-to parameter

runs:
  using: 'node16'
  main: 'dist/index.js'
