name: docker-build-cache-config
description: Effective cache with docker/build-push-action for pull request based development flow

inputs:
  image:
    description: Image repository to import/export cache
    required: true
  flavor:
    description: Flavor (multiline string)
    required: false
  extra-cache-from:
    description: Extra flag to cache-from
    required: false
  extra-cache-to:
    description: Extra flag to cache-to
    required: false
  pull-request-cache:
    description: Import and export the pull request cache
    required: false
    default: 'false'
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

outputs:
  cache-from:
    description: cache-from parameter for docker/build-push-action
  cache-to:
    description: cache-to parameter for docker/build-push-action

runs:
  using: 'node20'
  main: 'dist/index.js'
