name: docker-build-cache-config
description: Effective cache with docker/build-push-action for pull request based development flow

inputs:
  image:
    description: image name to import/export cache
    required: true
  tag-prefix:
    description: prefix of image tag
    required: false

outputs:
  cache-from:
    description: cache-from parameter
  cache-to:
    description: cache-to parameter

runs:
  using: 'node12'
  main: 'dist/index.js'
